# Generated by Django 3.2.6 on 2021-08-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auto_save',
            field=models.BooleanField(default=True),
        ),
    ]
